export const margins = {
  "&.m1": { margin: "$1" },
  "&.m2": { margin: "$2" },
  "&.m3": { margin: "$3" },
  "&.m4": { margin: "$4" },
  "&.m5": { margin: "$5" },
  "&.m6": { margin: "$6" },
  "&.m7": { margin: "$7" },
  "&.m8": { margin: "$8" },

  "&.mr1": { marginRight: "$1" },
  "&.mr2": { marginRight: "$2" },
  "&.mr3": { marginRight: "$3" },
  "&.mr4": { marginRight: "$4" },
  "&.mr5": { marginRight: "$5" },
  "&.mr6": { marginRight: "$6" },
  "&.mr7": { marginRight: "$7" },
  "&.mr8": { marginRight: "$8" },

  "&.ml1": { marginLeft: "$1" },
  "&.ml2": { marginLeft: "$2" },
  "&.ml3": { marginLeft: "$3" },
  "&.ml4": { marginLeft: "$4" },
  "&.ml5": { marginLeft: "$5" },
  "&.ml6": { marginLeft: "$6" },
  "&.ml7": { marginLeft: "$7" },
  "&.ml8": { marginLeft: "$8" },

  "&.mt1": { marginTop: "$1" },
  "&.mt2": { marginTop: "$2" },
  "&.mt3": { marginTop: "$3" },
  "&.mt4": { marginTop: "$4" },
  "&.mt5": { marginTop: "$5" },
  "&.mt6": { marginTop: "$6" },
  "&.mt7": { marginTop: "$7" },
  "&.mt8": { marginTop: "$8" },

  "&.mb1": { marginBottom: "$1" },
  "&.mb2": { marginBottom: "$2" },
  "&.mb3": { marginBottom: "$3" },
  "&.mb4": { marginBottom: "$4" },
  "&.mb5": { marginBottom: "$5" },
  "&.mb6": { marginBottom: "$6" },
  "&.mb7": { marginBottom: "$7" },
  "&.mb8": { marginBottom: "$8" },
};

export const paddings = {
  "&.p1": { padding: "$1" },
  "&.p2": { padding: "$2" },
  "&.p3": { padding: "$3" },
  "&.p4": { padding: "$4" },
  "&.p5": { padding: "$5" },
  "&.p6": { padding: "$6" },
  "&.p7": { padding: "$7" },
  "&.p8": { padding: "$8" },

  "&.pr1": { paddingRight: "$1" },
  "&.pr2": { paddingRight: "$2" },
  "&.pr3": { paddingRight: "$3" },
  "&.pr4": { paddingRight: "$4" },
  "&.pr5": { paddingRight: "$5" },
  "&.pr6": { paddingRight: "$6" },
  "&.pr7": { paddingRight: "$7" },
  "&.pr8": { paddingRight: "$8" },

  "&.pl1": { paddingLeft: "$1" },
  "&.pl2": { paddingLeft: "$2" },
  "&.pl3": { paddingLeft: "$3" },
  "&.pl4": { paddingLeft: "$4" },
  "&.pl5": { paddingLeft: "$5" },
  "&.pl6": { paddingLeft: "$6" },
  "&.pl7": { paddingLeft: "$7" },
  "&.pl8": { paddingLeft: "$8" },

  "&.pt1": { paddingTop: "$1" },
  "&.pt2": { paddingTop: "$2" },
  "&.pt3": { paddingTop: "$3" },
  "&.pt4": { paddingTop: "$4" },
  "&.pt5": { paddingTop: "$5" },
  "&.pt6": { paddingTop: "$6" },
  "&.pt7": { paddingTop: "$7" },
  "&.pt8": { paddingTop: "$8" },

  "&.pb1": { paddingBottom: "$1" },
  "&.pb2": { paddingBottom: "$2" },
  "&.pb3": { paddingBottom: "$3" },
  "&.pb4": { paddingBottom: "$4" },
  "&.pb5": { paddingBottom: "$5" },
  "&.pb6": { paddingBottom: "$6" },
  "&.pb7": { paddingBottom: "$7" },
  "&.pb8": { paddingBottom: "$8" },
};
